---
title: "Case Study 1"
author: "Rajat Chandna, Andy Ho, An Nguyen, Jodi Pafford, Tori Wheelis"
date: "June 6, 2018"
output:
  html_document:
    keep_md: yes
---


```{r}
#read in Beers data set with correct character formatting.
Beers <- read.csv("Beers.csv", header=TRUE, fileEncoding = 'UTF-8')

UniqueBeers <- Beers[!duplicated(Beers[c(1,3,4,5,6,7)]),]

byBrewery <- split(UniqueBeers, UniqueBeers$Brewery_id) #Group beers by Brewery

# Match First 3 Chars
for(i in 1:length(byBrewery)){
  uniTempVec <- unique(byBrewery[[i]]$Name)
  tempListVec <- character()
  for(i in 1:length(uniTempVec)){
    subTobeSearched <- substr(uniTempVec[i], 1,3)
    subTobeSearched <- paste0("^",subTobeSearched)
    tempVec <- unique(grep(subTobeSearched, uniTempVec, ignore.case = T, value = T))
    if(length(tempVec) > 1){
      tempListVec <- c(tempListVec, paste(" ", tempVec, collapse = " "))
    }
  }

  unitempListVec <- unique(tempListVec)
  for(i in 1:length(unitempListVec)){
    temp2Vec <- as.vector(unlist(strsplit(trimws(unitempListVec[i], "l"), "   ")))
    if(length(temp2Vec) > 1){
      for(i in 1:length(temp2Vec)){
        cat(temp2Vec[i], file = "./First3matches.csv", append = T)
        if(i != length(temp2Vec)){
          cat(", ", file = "./First3matches.csv", append = T)
        }  
      }
      cat("\n", file = "./First3matches.csv", append = T)
    }
  }
}


# Match Last 3 chars
for(i in 1:length(byBrewery)){
  uniTempVec <- as.character(unique(byBrewery[[i]]$Name))
  tempListVec <- character()
  for(i in 1:length(uniTempVec)){
    subTobeSearched <- substr(uniTempVec[i], nchar(uniTempVec[i]) - 3, nchar(uniTempVec[i]))
    subTobeSearched <- paste0("^",subTobeSearched)
    tempVec <- unique(grep(subTobeSearched, uniTempVec, ignore.case = T, value = T))
    if(length(tempVec) > 1){
      tempListVec <- c(tempListVec, paste(" ", tempVec, collapse = " "))
    }
  }

  unitempListVec <- unique(tempListVec)
  for(i in 1:length(unitempListVec)){
    temp2Vec <- as.vector(unlist(strsplit(trimws(unitempListVec[i], "l"), "   ")))
    if(length(temp2Vec) > 1){
      for(i in 1:length(temp2Vec)){
        cat(temp2Vec[i], file = "./Last3matches.csv", append = T)
        if(i != length(temp2Vec)){
          cat(", ", file = "./Last3matches.csv", append = T)
        }  
      }
      cat("\n", file = "./Last3matches.csv", append = T)
    }
  }
}
```

####Tidying Breweries Data
```{r}
#Tidying Breweries.csv Section. Completed by Rajat and Andy
#First inspect the State column.  We listed out the States and got the count for each.  If observation > 50, we investigated further by examining all the States with a count of 1 (DC, ND, SD, WV).  In this case, there was 51 States and confirmed the 51st was DC which is acceptable.  All abbreviations in State column is valid.
breweries <- read.csv("Breweries.csv", header = TRUE)
str(breweries)
summary(breweries)
table(breweries$State)
```

```{r}
#In this section, looking to clean up the "City" column.  Still looking for a more elequent code but for now creating subsets for each letter and visually identifying misspellings, abbreviations, and/or punctuations.  Rajat to research a function that creates a subset of cities by subsetting cities with the same 3 letter string.
unique(breweries[grep("[.]", breweries$City), "City"])
unique(breweries[grep("^[Mm].*", breweries$City), "City"])
unique(breweries[grep("^[Ss].*", breweries$City), "City"])
```

```{r}
#With State and City cleaned up, we check for duplicates breweries by matching the name, each's city, than state.  Still in process.
```